Page1/urls.py
from django.urls import path
from .views import *
app_name='shop'
urlpatterns=[
    path('',home,name='home'),
    path('add/',create_view,name='add'),
    path('list/',viewss,name='all'),
    path('<id>/delete/',delete_view,name='delete'),
    path('<id>/update/',update_view,name='update'),
    path("add/<int:product_id>/", add_to_cart, name="add_to_cart"),
    path("remove/<int:cart_item_id>/", remove_from_cart, name="remove_from_cart"),
    path("cart/", cart_detail, name="cart_detail"),

    path('product/<int:product_id>/', product_detail, name='add_cart'),


]

accounts/urls.py
from .views import *
from django.urls import path
urlpatterns=[
    path('signup/',register,name='signup')

]

main/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',include('Page1.urls'))]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Page1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250)
    def __str__(self):
        return self.name

class Products(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    description=models.TextField()
    data=models.DateField(auto_now_add=True)
    image=models.ImageField(upload_to='images/',blank=True)


    def __str__(self):
        return str(self.title)
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f" {Products.title}=>{self.quantity} x {(Products.objects.get(id=self.product.id)).price}"

    def get_absolute_url(self):
        return reverse("home")

accounts/models.py
from django.db import models

# Create your models here.

Page1/forms.py
from django.forms import ModelForm
from .models import *
class PostForm(ModelForm):
    class Meta:
        model=Products
        fields=('__all__')

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,User

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

Page1/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import *
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib import messages
# Create your views here.
def home(request):
    return render(request,'Page1/home.html')

@login_required
def create_view(request):
    if request.method=="POST":
        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/list/')

    else:
        form=PostForm()
        return render(request,'Page1/create_view.html',{'form':form})

def viewss(request):
    context={}
    context['dataset']=Products.objects.all()
    if request.method == "POST":
        messages.success(request, f"{Products.title} added to your cart.")
        return redirect("shop:add_to_cart")

    return render(request, 'Page1/list_view.html', context)
@login_required
def delete_view(request,id):
    object=get_object_or_404(Products,id=id)
    if request.method=="POST":
        object.delete()
        return redirect('/list/')
    context={}
    return render(request,'Page1/delete.html',context)
@login_required
def update_view(request,id):
    obj=get_object_or_404(Products,id=id)
    form=PostForm(request.POST or None,instance=obj)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/list/')
    context={}
    context["form"]=form
    return render(request,'Page1/update.html',context)


# @login_required
# def product_detail(request,product_id):
#     product = Products.objects.filter(id=product_id)
#
#     if request.method == "POST":
#         messages.success(request, f"{product.name} added to your cart.")
#         return redirect("shop:add_to_cart", id=product_id)
#
#     context = {
#         "products": product,
#     }
#     return render(request,'Page1/product_detail.html',context)
@login_required
def add_to_cart(request,product_id):
    try:
        cart_item = Cart.objects.get(user=request.user, product_id=product_id)
        if cart_item:
            cart_item.quantity += 1
            cart_item.save()
            messages.success(request, "Item added to your cart.")
    except:
        Cart.objects.create(user=request.user, product_id=product_id)
        messages.success(request, "Item added to your cart.")

    return redirect("shop:cart_detail")

@login_required
def remove_from_cart(request, cart_item_id):
    cart_item = get_object_or_404(Cart, id=cart_item_id)

    if cart_item.user == request.user:
        cart_item.delete()
        messages.success(request, "Item removed from your cart.")

    return redirect("shop:cart_detail")

@login_required
def cart_detail(request):
    cart_items = Cart.objects.filter(user=request.user)
    total_price = sum(item.quantity * item.product.price for item in cart_items)

    context = {
        "cart_items": cart_items,
        "total_price": total_price,
    }

    return render(request, "Page1/cart_detail.html", context)

@login_required
def product_detail(request, pk):
    product = get_object_or_404(Products, id=pk)

    if request.method == "POST":
        messages.success(request, f"{product.name} added to your cart.")
        return redirect("shop:add_to_cart", product_id=pk)

    context = {
        "product": product,
    }

    return render(request, "Page1/product_detail.html", context)

accounts/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm
from django.http import HttpResponseRedirect
def register(response):
    try:
        if response.method == "POST":
            form= RegisterForm(response.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
    except:
            form = RegisterForm()
            return render(response, "registration/signup.html", {'form':form})

Page1/templates/Page1/add_to_cart.html
{% extends "Page1/base.html" %}

{% block content %}
    {{ message }}

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Add to Cart">
    </form>
{% endblock %}

Page1/templates/Page1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
        <h2> Welcome to Shopping</h2>
    {%if user.is_authenticated%}
         <a href="{% url 'logout'%}">Logout</a>
        <a href="{%url 'shop:all' %}">Shopping</a>
        <a href="{% url 'shop:add'%}">Create</a>

    <br>

{%else%}
        <a href="{%url 'signup' %}">Sign UP</a>
            <a href="{%url 'login' %}">Login</a>
         <a href="{%url 'shop:all' %}">Shopping</a>
{%endif%}
{%block content%}
{%endblock%}
</body>
</html>

Page1/templates/Page1/cart_detail.html
{% extends "Page1/base.html" %}
{% block content %}
        <table class="table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total Price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                    <tr>
                        <td>{{ item.product }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.product.price }}</td>
                        <td>{%widthratio item.quantity 1 item.product.price%} </td>

                       <td><a href="{% url 'shop:remove_from_cart' item.id %}">Remove</a></td>



                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3"></td>
                    <td>Total: </td>
                    <td>{{ total_price }}</td>
                </tr>
            </tfoot>
        </table>






{% endblock %}

Page1/templates/Page1/create_view.html
{% extends 'Page1/base.html' %}
{% block content %}

    <form  method="post" enctype="multipart/form-data">

      {% csrf_token %}
      {{form.as_p}}

       <input type="submit" value="Publish">
    </form>


    {% if img_obj %}
        <img src="{{ img_object.image.url}}" alt="connect" style="max-height:300px">
    {% endif %}
{%endblock%}

Page1/templates/Page1/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
<form method="POST">
    {%csrf_token%}
    <h2>Do you really want to delete? </h2>
    <input type="submit" value="Confirm">
    </form>
</body>
</html>

Page1/templates/Page1/home.html
{%extends 'Page1/base.html'%}
{%block content %}
{%if user.is_authenticated%}
    <h2 >Hello {{user.username}}</h2>

{%endif%}
{%endblock%}

Page1/templates/Page1/list_view.html
{%extends 'Page1/base.html'%}
{% block content %}
{%load static%}
    <table class="table" >
      <tbody>
      {% for employee in dataset %}
      <tr>
        <td>{{ employee.category }}  </td>
        <td>{{ employee.title}}</td>
        <td>{{ employee.price}}</td>
          {% if employee.image %}
        <td><a href="{% url 'shop:cart_detail'  %}">Cart</a></td>
            <td><a href="{% url 'shop:add_to_cart' employee.id  %}">Add</a></td>
          <td><img src="{{ employee.image.url }}" width='200'/></td>
          {% endif %}

      </tr>
      {% endfor %}
    </tbody>
            </tbody>

        </table>

{%endblock%}

Page1/templates/Page1/product_detail.html
{% extends "Page1/base.html" %}
{% block content %}

    <table class="table">

            <thead>
                <tr>
                    <th>Products</th>

                    <th>Price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td>{{ product.title }}</td>

                        <td>{{ product.price }}</td>
                        <td><a href="{% url 'shop:cart_detail'  %}">Cart</a></td>
                        <td><a href="{% url 'shop:add_to_cart' product.id  %}">Add</a></td>

                    </tr>
                {% endfor %}
            </tbody>

        </table>

{%endblock%}

Page1/templates/Page1/remove_from_cart.html
{% extends "Page1/base.html" %}
{% block content %}

    {{ message }}

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Remove from Cart">
    </form>
{% endblock %}

Page1/templates/Page1/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit"  value="Update">
    </form>
</body>
</html>